[build]
builder = "dockerfile"
dockerfilePath = "assignment1/Dockerfile"
buildContext = "assignment1"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10